FROM python:3.9

RUN apt-get install curl
RUN pip install pandas argparse psycopg2-binary sqlalchemy python-dotenv

WORKDIR /app
COPY .env .env
COPY data-ingest-csv.py data-ingest-csv.py

ENTRYPOINT [ "python", "data-ingest-csv.py" ]