services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_HOSTNAME}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT_CONTAINER}
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT_LOCAL}:${PGADMIN_PORT_CONTAINER}
    depends_on:
      - postgres
    links:
      - postgres:db