FROM python:3.9

RUN apt-get install curl
RUN pip install pandas pyarrow argparse psycopg2-binary sqlalchemy python-dotenv

WORKDIR /app
COPY .env .env
COPY data-ingest-parquet.py data-ingest-parquet.py

ENTRYPOINT [ "python", "data-ingest-parquet.py" ]