services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5431:5432
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    container_name: database
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    container_name: database-gui
    depends_on:
      - postgres
    links:
      - "postgres:database"