FROM python:3.9

RUN apt-get install curl
RUN pip install pandas pyarrow psycopg2-binary sqlalchemy argparse

WORKDIR /app
COPY data-ingest-parquet.py data-ingest-parquet.py

ENTRYPOINT [ "python", "data-ingest-parquet.py" ]